### ISSUE TITLE
Cannot use unquotes in DEFINE-SCRIPT body on SBCL

### ISSUE THREAD

**Issue by goose121** [TBRSS/overlord#18]
I haven't tested this on other impls, but in SBCL at least, the `,` reader macro is implemented as a struct `sb-impl::comma`, and `murmurhash` has no method applicable to it. Thus, when the `defconfig` form that `define-script` expands to tries to hash the method body, an error is signalled. This also affects other forms that expand to a `define-script` call, such as `defpattern`.

A possible portable solution could be to define a method on `murmurhash` for all `structure-object`s based on hashing all of their slots as well as their class, however this could have unwanted consequences for other user-defined structures and is probably a bad idea. Another could be to use the MOP in the same way, but instead specialize the method to the `class-of` whatever a `,` is read as, provided that it is a `structure-object` or `standard-object`; this would be more specific to the `,` reader macro, but seems like a hacky solution, especially given the best code I could think of to obtain the class is probably undefined behaviour:
```
(class-of (progn `#1=,nil #1#))
```
A third solution would be to change the default hash function from `murmurhash` to either `sxhash` or a generic function, which would be more customizable than `sxhash` and could use `sxhash` as a fallback.

**Comment by ruricolist** [comment]
Thank you for the detailed bug report.

The drawback of `sxhash` is that it is useless for structs: all instances of the same structure class share the same hash. There is a good discussion on [Stack Overflow](https://stackoverflow.com/questions/21126507/why-does-sxhash-return-a-constant-for-all-structs).

My preferred solution to this problem is to sidestep it by using [fare-quasiquote](https://github.com/fare/fare-quasiquote).

**Comment by goose121** [comment]
Oh, wow; I didn't know that particular detail, and that is an irritating downside. fare-quasiquote does seem like a solution that ought to work though, thank you.
